export const EventsEnum = {
    INCOMING_DATA: 'INCOMING_DATA',
    DEVICE_CONNECTED: 'DEVICE_CONNECTED',
    DEVICE_DISCONNECTED: 'DEVICE_DISCONNECTED',
    GLOBAL_TIMER_START: 'GLOBAL_TIMER_START',
    GLOBAL_TIMER_STOP: 'GLOBAL_TIMER_STOP',
    GLOBAL_TIMER_TICK: 'GLOBAL_TIMER_TICK',
    GLOBAL_TIMER_RESET: 'RESET_GLOBAL_TIMER',
    CLEAR_SPECTRUM: 'CLEAR_SPECTRUM'
}