export const enum EventsEnum {
    INCOMING_DATA = 'INCOMING_DATA',
    RESET_SESSION = 'RESET_SESSION',
    DEVICE_CONNECTED = 'DEVICE_CONNECTED',
    DEVICE_DISCONNECTED = 'DEVICE_DISCONNECTED',
    GLOBAL_TIMER_START = 'GLOBAL_TIMER_START',
    GLOBAL_TIMER_STOP = 'GLOBAL_TIMER_STOP',
    GLOBAL_TIMER_TICK = 'GLOBAL_TIMER_TICK',
    GLOBAL_TIMER_RESET = 'GLOBAL_TIMER_RESET',
    CLEAR_SPECTRUM = 'CLEAR_SPECTRUM'
}